services:
  # Postgres Configuration
  postgres:
    image: postgres:12
    volumes:
      - database:/var/lib/postgresql/data
      - app:/app
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: arweave
      POSTGRES_PASSWORD: arweave
      POSTGRES_DB: arweave
    command: -p 5432
    networks:
      - sub-etha
  # Arweave Node Configurations
  arweave-node:
    image: lucaarweave/arweave-node:0.0.1
    expose: 
      - 1984
    ports:
      - "1984:1984"
    environment:
      AR_RUNMODE: test
    volumes:
      - "ardata:/mnt/arweave-data"
    restart: "always"
    networks:
      - sub-etha
  # Arweave Gateway configuration
  arweave-gateway:
    image: lucaarweave/arweave-gateway:0.0.1
    volumes:
      - app:/app
    links: 
      - postgres
      - arweave-node
    expose: 
      - 3000
    ports:
      - "3000:3000"
    networks:
      - sub-etha
  # The TestWeave net
  testweave:
    image: "reverseproxy:1.0.0"
    container_name: testweave
    build:
      context: .
      dockerfile: ./docker/proxy.dockerfile
    links: 
      - postgres
      - arweave-node
      - arweave-gateway
      - faucet
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      - sub-etha
  faucet:
    image: "faucet:1.0.0"
    container_name: faucet
    build:
      context: .
      dockerfile: ./docker/faucet.dockerfile
    links: 
      - postgres
      - arweave-node
      - arweave-gateway
    ports:
      - "4000:4000"
    expose:
      - 4000
    networks:
      - sub-etha
volumes:
  app:
  database:
  ardata:
networks: 
  sub-etha: